# Generated by Django 3.2.13 on 2023-12-05 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advinterface', '0002_auto_20231205_0337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='cis_classes',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='communication_classes',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='component_area_classes',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='mathematics_class',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='social_sciences_class',
        ),
        migrations.DeleteModel(
            name='CISClass',
        ),
        migrations.DeleteModel(
            name='CommunicationClass',
        ),
        migrations.DeleteModel(
            name='ComponentAreaClass',
        ),
        migrations.DeleteModel(
            name='MathematicsClass',
        ),
        migrations.DeleteModel(
            name='SocialSciencesClass',
        ),
    ]
