# Generated by Django 3.2.13 on 2023-12-05 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advinterface', '0004_alter_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedCISElective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CISClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ComponentAreaClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MathematicsClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SocialSciencesClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='transcript_upload',
            field=models.FileField(blank=True, null=True, upload_to='transcripts/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='advanced_cis_electives',
            field=models.ManyToManyField(blank=True, related_name='advanced_cis_electives', to='advinterface.AdvancedCISElective'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cis_classes',
            field=models.ManyToManyField(blank=True, related_name='cis_classes', to='advinterface.CISClass'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='communication_classes',
            field=models.ManyToManyField(blank=True, related_name='communication_classes', to='advinterface.CommunicationClass'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='component_area_classes',
            field=models.ManyToManyField(blank=True, related_name='component_area_classes', to='advinterface.ComponentAreaClass'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mathematics_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='advinterface.mathematicsclass'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='social_sciences_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='advinterface.socialsciencesclass'),
        ),
    ]
