# Generated by Django 3.2.13 on 2023-12-05 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advinterface', '0005_auto_20231205_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mathematics_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mathematics_class', to='advinterface.mathematicsclass'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='social_sciences_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_sciences_class', to='advinterface.socialsciencesclass'),
        ),
    ]
